/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemlogin;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agung
 */
public class ListUser extends javax.swing.JFrame {

    /**
     * Creates new form ListUser
     */
    private Connection con;
    private int userId;
    
    public ListUser(int userId) {
        initComponents();
        this.con = (Connection)SistemLogin.connect();
        this.userId = userId;   
        try {
            Statement query = con.createStatement();
            ResultSet rs = query.executeQuery("SELECT * FROM list_user");
            int rowNumber = 0;
            while (rs.next()) {
                rowNumber++;
            }
            rs = query.executeQuery("SELECT * FROM list_user");
            ResultSetMetaData rsMd = rs.getMetaData();
            int numbers = rsMd.getColumnCount();
//            numbers++;
//            System.out.println(numbers);
            String[] columnName = new String[numbers];
            for (int i = 0; i < numbers; i++) {
//                if (i < numbers-1) {
//                    System.out.println(rsMd.getColumnName(i+1));
                    columnName[i] = rsMd.getColumnName(i+1);
//                } else {
//                    columnName[i] = "Action";
//                }
            }
            Object dataTable[][] = new Object[rowNumber][numbers];
            int row = 0;
            while (rs.next()) {                
                dataTable[row][0] = rs.getString(1);
                dataTable[row][1] = rs.getString(2);                
                dataTable[row][2] = rs.getString(3);

                dataTable[row][3] = rs.getString(4);
                if (rs.getInt(5) == 1) {
                    dataTable[row][4] = "Admin";
                } else{
                    dataTable[row][4] = "User";
                }
                
//                dataTable[row][5] = new Button("Update");
                row++;
            }
            
            DefaultTableModel tableModel = new DefaultTableModel(dataTable, columnName){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };

            listUser.setModel(tableModel);
            listUser.getColumnModel().getColumn(0).setPreferredWidth(rsMd.getColumnDisplaySize(1));
            listUser.getColumnModel().getColumn(0).setResizable(false);
            listUser.getColumnModel().getColumn(1).setPreferredWidth(rsMd.getColumnDisplaySize(2));
            listUser.getColumnModel().getColumn(1).setResizable(false);
            listUser.getColumnModel().getColumn(2).setPreferredWidth(rsMd.getColumnDisplaySize(3));
            listUser.getColumnModel().getColumn(2).setResizable(false);
            listUser.getColumnModel().getColumn(3).setPreferredWidth(rsMd.getColumnDisplaySize(4));
            listUser.getColumnModel().getColumn(3).setResizable(false);
            listUser.getColumnModel().getColumn(4).setPreferredWidth(rsMd.getColumnDisplaySize(5));
            listUser.getColumnModel().getColumn(4).setResizable(false);
        
        } catch(SQLException e) {
            Logger.getLogger(ListUser.class.getName()).log(Level.SEVERE, null, e);
        }
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        int centerX = (screenSize.width - getWidth()) / 2;
        int centerY = (screenSize.height - getHeight()) / 2;
        
        setLocation(centerX, centerY);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List User");
        jLabel1.setToolTipText("");

        listUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Email", "Role", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listUser);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            setVisible(false);
            new Home(this.userId);
        } catch (SQLException ex) {
            Logger.getLogger(ListUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listUser;
    // End of variables declaration//GEN-END:variables
}
